
import React, { useState, useRef } from 'react';
import { PlantCareInfo } from '../types';

interface PlantCareCardProps {
  plant: PlantCareInfo;
  imageUrl?: string;
  onSave?: (nickname: string) => void;
  isSaved?: boolean;
  nickname?: string;
}

const PlantCareCard: React.FC<PlantCareCardProps> = ({ plant, imageUrl, onSave, isSaved, nickname }) => {
  const [localNickname, setLocalNickname] = useState('');
  const [showSeasonal, setShowSeasonal] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const difficultyConfig = {
    Easy: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', icon: 'fa-face-smile' },
    Moderate: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', icon: 'fa-face-meh' },
    Expert: { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200', icon: 'fa-skull' },
  };

  const diff = difficultyConfig[plant.difficulty || 'Easy'];

  const seasonIcons: Record<string, string> = {
    spring: 'fa-seedling',
    summer: 'fa-sun',
    fall: 'fa-leaf',
    winter: 'fa-snowflake',
  };

  const seasonColors: Record<string, string> = {
    spring: 'bg-green-50 text-green-600 border-green-100',
    summer: 'bg-amber-50 text-amber-600 border-amber-100',
    fall: 'bg-orange-50 text-orange-600 border-orange-100',
    winter: 'bg-blue-50 text-blue-600 border-blue-100',
  };

  const handleShare = async () => {
    const text = `${plant.commonName} (${plant.scientificName})\n\nWatering: ${plant.watering}\nLight: ${plant.light}\nDifficulty: ${plant.difficulty || 'N/A'}\n\n${plant.description}`;
    
    if (navigator.share) {
      try {
        await navigator.share({ title: `${plant.commonName} Care Guide - SproutSage`, text });
      } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      setShowShareMenu(true);
      setTimeout(() => setShowShareMenu(false), 2000);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html><head><title>${plant.commonName} Care Guide</title>
      <style>
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
        h1 { font-size: 28px; margin-bottom: 4px; }
        h2 { font-size: 18px; color: #059669; margin-top: 24px; }
        .sci { font-style: italic; color: #666; font-size: 14px; }
        .section { background: #f9fafb; padding: 16px; border-radius: 12px; margin: 12px 0; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .label { font-weight: 700; font-size: 12px; text-transform: uppercase; color: #999; margin-bottom: 4px; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
      </style></head><body>
      <h1>${plant.commonName}</h1>
      <p class="sci">${plant.scientificName}</p>
      ${plant.difficulty ? `<p><span class="badge" style="background:#ecfdf5;color:#059669;">${plant.difficulty}</span></p>` : ''}
      <p>${plant.description}</p>
      <div class="grid">
        <div class="section"><div class="label">Watering</div><p>${plant.watering}</p></div>
        <div class="section"><div class="label">Light</div><p>${plant.light}</p></div>
        <div class="section"><div class="label">Temperature</div><p>${plant.temperature}</p></div>
        <div class="section"><div class="label">Soil</div><p>${plant.soil}</p></div>
      </div>
      <div class="section"><div class="label">Fertilizer</div><p>${plant.fertilizer}</p></div>
      ${plant.toxicity ? `<div class="section" style="background:${plant.toxicity.toxicToPets ? '#fef2f2' : '#f0fdf4'};border:1px solid ${plant.toxicity.toxicToPets ? '#fecaca' : '#bbf7d0'}">
        <div class="label">Safety</div>
        <p>${plant.toxicity.toxicToPets ? 'Toxic to pets' : 'Safe for pets'} | ${plant.toxicity.toxicToHumans ? 'Toxic to humans' : 'Safe for humans'}</p>
        <p>${plant.toxicity.details}</p></div>` : ''}
      ${plant.seasonalCare ? `<h2>Seasonal Care</h2>
        <div class="grid">
          <div class="section"><div class="label">Spring</div><p>${plant.seasonalCare.spring}</p></div>
          <div class="section"><div class="label">Summer</div><p>${plant.seasonalCare.summer}</p></div>
          <div class="section"><div class="label">Fall</div><p>${plant.seasonalCare.fall}</p></div>
          <div class="section"><div class="label">Winter</div><p>${plant.seasonalCare.winter}</p></div>
        </div>` : ''}
      ${plant.propagation ? `<div class="section"><div class="label">Propagation</div><p>${plant.propagation}</p></div>` : ''}
      <p style="margin-top:32px;font-size:11px;color:#aaa;">Generated by SproutSage AI</p>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div ref={cardRef} className="bg-white rounded-3xl shadow-xl overflow-hidden border border-emerald-100 transition-all duration-300 hover:shadow-2xl">
      {imageUrl && (
        <div className="h-64 sm:h-80 overflow-hidden relative">
          <img src={imageUrl} alt={plant.commonName} className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent"></div>
          <div className="absolute bottom-4 left-4 right-4 text-white">
            {nickname && <h3 className="text-emerald-300 font-bold uppercase tracking-widest text-xs mb-1">"{nickname}"</h3>}
            <h2 className="text-3xl font-bold">{plant.commonName}</h2>
            <p className="italic opacity-90 text-sm font-medium">{plant.scientificName}</p>
          </div>
          {/* Difficulty badge on image */}
          <div className="absolute top-4 right-4 flex gap-2">
            <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold backdrop-blur-md ${diff.bg}/80 ${diff.text}`}>
              <i className={`fa-solid ${diff.icon}`}></i>
              {plant.difficulty || 'Easy'}
            </span>
          </div>
          {/* Share button */}
          <div className="absolute top-4 left-4 relative">
            <button
              onClick={handleShare}
              className="w-9 h-9 bg-white/20 backdrop-blur-md text-white rounded-xl flex items-center justify-center hover:bg-white/30 transition-colors"
              title="Share"
            >
              <i className="fa-solid fa-share-nodes text-sm"></i>
            </button>
            {showShareMenu && (
              <div className="absolute top-full left-0 mt-2 bg-white text-gray-800 text-xs font-semibold px-3 py-2 rounded-lg shadow-lg whitespace-nowrap">
                <i className="fa-solid fa-check text-emerald-500 mr-1"></i> Copied to clipboard!
              </div>
            )}
          </div>
        </div>
      )}
      
      <div className="p-6">
        {!imageUrl && (
          <div className="mb-6">
            {nickname && <h3 className="text-emerald-600 font-bold uppercase tracking-widest text-xs mb-1">"{nickname}"</h3>}
            <h2 className="text-3xl font-bold text-emerald-900">{plant.commonName}</h2>
            <p className="italic text-emerald-600 font-medium">{plant.scientificName}</p>
            {plant.difficulty && (
              <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold mt-2 ${diff.bg} ${diff.text}`}>
                <i className={`fa-solid ${diff.icon}`}></i>
                {plant.difficulty} Care
              </span>
            )}
          </div>
        )}

        <p className="text-gray-600 mb-6 leading-relaxed">
          {plant.description}
        </p>

        {/* Toxicity Warning */}
        {plant.toxicity && (plant.toxicity.toxicToPets || plant.toxicity.toxicToHumans) && (
          <div className="mb-6 p-4 rounded-2xl border-2 border-rose-200 bg-rose-50/50">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-rose-100 rounded-xl flex items-center justify-center text-rose-600 shrink-0 mt-0.5">
                <i className="fa-solid fa-triangle-exclamation"></i>
              </div>
              <div>
                <h4 className="font-bold text-rose-900 mb-1">Toxicity Warning</h4>
                <div className="flex gap-2 mb-2">
                  {plant.toxicity.toxicToPets && (
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-rose-100 text-rose-700 rounded-full text-[10px] font-bold">
                      <i className="fa-solid fa-paw"></i> Toxic to Pets
                    </span>
                  )}
                  {plant.toxicity.toxicToHumans && (
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-rose-100 text-rose-700 rounded-full text-[10px] font-bold">
                      <i className="fa-solid fa-child"></i> Toxic to Humans
                    </span>
                  )}
                </div>
                <p className="text-sm text-rose-700">{plant.toxicity.details}</p>
              </div>
            </div>
          </div>
        )}

        {plant.toxicity && !plant.toxicity.toxicToPets && !plant.toxicity.toxicToHumans && (
          <div className="mb-6 p-4 rounded-2xl border border-emerald-200 bg-emerald-50/50 flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center text-emerald-600 shrink-0">
              <i className="fa-solid fa-shield-check"></i>
            </div>
            <div>
              <h4 className="font-bold text-emerald-900 text-sm">Safe for Family</h4>
              <p className="text-xs text-emerald-700">Non-toxic to pets and humans</p>
            </div>
          </div>
        )}

        {/* Care Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
          <div className="flex items-start gap-3 p-4 bg-blue-50 rounded-2xl">
            <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center text-blue-600 shrink-0">
              <i className="fa-solid fa-droplet"></i>
            </div>
            <div>
              <h4 className="font-bold text-blue-900 text-sm">Watering</h4>
              <p className="text-xs text-blue-700">{plant.watering}</p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 bg-amber-50 rounded-2xl">
            <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center text-amber-600 shrink-0">
              <i className="fa-solid fa-sun"></i>
            </div>
            <div>
              <h4 className="font-bold text-amber-900 text-sm">Light</h4>
              <p className="text-xs text-amber-700">{plant.light}</p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 bg-orange-50 rounded-2xl">
            <div className="w-10 h-10 bg-orange-100 rounded-xl flex items-center justify-center text-orange-600 shrink-0">
              <i className="fa-solid fa-temperature-half"></i>
            </div>
            <div>
              <h4 className="font-bold text-orange-900 text-sm">Temperature</h4>
              <p className="text-xs text-orange-700">{plant.temperature}</p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 bg-emerald-50 rounded-2xl">
            <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center text-emerald-600 shrink-0">
              <i className="fa-solid fa-seedling"></i>
            </div>
            <div>
              <h4 className="font-bold text-emerald-900 text-sm">Soil</h4>
              <p className="text-xs text-emerald-700">{plant.soil}</p>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <div className="bg-slate-50 p-4 rounded-2xl">
            <h4 className="font-bold text-slate-800 mb-1.5 flex items-center gap-2 text-sm">
              <i className="fa-solid fa-vial-circle-check text-emerald-500"></i>
              Fertilizer
            </h4>
            <p className="text-xs text-slate-600">{plant.fertilizer}</p>
          </div>

          <div className="bg-red-50 p-4 rounded-2xl">
            <h4 className="font-bold text-red-800 mb-2 flex items-center gap-2 text-sm">
              <i className="fa-solid fa-bug text-red-500"></i>
              Potential Pests
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {plant.pests.map((pest, i) => (
                <span key={i} className="px-2.5 py-1 bg-white border border-red-100 text-red-700 rounded-full text-[10px] font-semibold">
                  {pest}
                </span>
              ))}
            </div>
          </div>

          {/* Propagation */}
          {plant.propagation && (
            <div className="bg-teal-50 p-4 rounded-2xl">
              <h4 className="font-bold text-teal-800 mb-1.5 flex items-center gap-2 text-sm">
                <i className="fa-solid fa-clone text-teal-500"></i>
                Propagation
              </h4>
              <p className="text-xs text-teal-700">{plant.propagation}</p>
            </div>
          )}

          {/* Common Varieties */}
          {plant.commonVarieties && plant.commonVarieties.length > 0 && (
            <div className="bg-violet-50 p-4 rounded-2xl">
              <h4 className="font-bold text-violet-800 mb-2 flex items-center gap-2 text-sm">
                <i className="fa-solid fa-palette text-violet-500"></i>
                Popular Varieties
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {plant.commonVarieties.map((variety, i) => (
                  <span key={i} className="px-2.5 py-1 bg-white border border-violet-100 text-violet-700 rounded-full text-[10px] font-semibold">
                    {variety}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Seasonal Care */}
          {plant.seasonalCare && (
            <div>
              <button
                onClick={() => setShowSeasonal(!showSeasonal)}
                className="w-full flex items-center justify-between p-4 bg-gradient-to-r from-emerald-50 to-teal-50 rounded-2xl border border-emerald-100 hover:border-emerald-200 transition-colors"
              >
                <span className="font-bold text-emerald-800 flex items-center gap-2 text-sm">
                  <i className="fa-solid fa-calendar-days text-emerald-500"></i>
                  Seasonal Care Guide
                </span>
                <i className={`fa-solid fa-chevron-down text-emerald-400 transition-transform ${showSeasonal ? 'rotate-180' : ''}`}></i>
              </button>
              {showSeasonal && (
                <div className="grid grid-cols-2 gap-3 mt-3 animate-in fade-in slide-in-from-top-2 duration-200">
                  {(['spring', 'summer', 'fall', 'winter'] as const).map((season) => (
                    <div key={season} className={`p-3 rounded-xl border ${seasonColors[season]}`}>
                      <div className="flex items-center gap-1.5 mb-1">
                        <i className={`fa-solid ${seasonIcons[season]} text-xs`}></i>
                        <span className="text-[10px] font-bold uppercase tracking-wider capitalize">{season}</span>
                      </div>
                      <p className="text-[11px] leading-relaxed opacity-90">{plant.seasonalCare[season]}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          <div className="bg-purple-50 p-4 rounded-2xl border-l-4 border-purple-400">
            <h4 className="font-bold text-purple-800 mb-1 text-sm">Did you know?</h4>
            <p className="text-xs text-purple-700 italic">"{plant.funFact}"</p>
          </div>
        </div>

        {/* Actions */}
        <div className="mt-6 flex gap-2">
          <button
            onClick={handlePrint}
            className="flex-1 py-3 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 bg-gray-100 text-gray-600 hover:bg-gray-200"
          >
            <i className="fa-solid fa-print"></i>
            Print Care Guide
          </button>
          <button
            onClick={handleShare}
            className="flex-1 py-3 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 bg-gray-100 text-gray-600 hover:bg-gray-200"
          >
            <i className="fa-solid fa-share-nodes"></i>
            Share
          </button>
        </div>

        {onSave && !isSaved && (
          <div className="mt-4 space-y-3">
            <div>
              <label className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Give it a nickname (Optional)</label>
              <input 
                type="text" 
                value={localNickname}
                onChange={(e) => setLocalNickname(e.target.value)}
                placeholder="e.g. Fernie Sanders, Sir Grows-a-lot..."
                className="w-full px-5 py-3 rounded-2xl border border-emerald-100 outline-none focus:border-emerald-500 text-gray-700 bg-emerald-50/30 transition-colors"
              />
            </div>
            <button 
              onClick={() => onSave(localNickname)}
              className="w-full py-4 rounded-2xl font-bold flex items-center justify-center gap-2 transition-all bg-emerald-600 text-white hover:bg-emerald-700 shadow-lg shadow-emerald-200 active:scale-[0.98]"
            >
              <i className="fa-solid fa-plus"></i>
              Add to My Garden
            </button>
          </div>
        )}

        {isSaved && (
          <div className="mt-4 w-full py-3 rounded-2xl font-bold flex items-center justify-center gap-2 bg-emerald-50 text-emerald-600 text-sm">
            <i className="fa-solid fa-check-circle"></i>
            In Your Garden
          </div>
        )}
      </div>
    </div>
  );
};

export default PlantCareCard;
